[App]
Name = "h2o-olympics-challenge-wildfires"
Version = "2.0"
Title = "H2O Olympics - Wildfire Challenge Starter Kit"
Description = "Wildfire Challenge Starter Kit Wave App."
LongDescription = "about.md"
Tags = ["STARTER_KITS"]

[Runtime]
Module = "src.app"
MemoryLimit = "5Gi"
MemoryReservation = "1Gi"
