[App]
Name = "challenge-wildfires-submission-<fill your team name>"
Version = "1.0"
Title = "Wildfire Challenge Submission Title <Team>"
Description = "Wildfire Challenge Submission Description <Team>."
LongDescription = "about.md"
Tags = ["WILDFIRES"]

[Runtime]
Module = "src.app"
MemoryLimit = "5Gi"
MemoryReservation = "1Gi"
